name: build

on:
  push:
    branches: [ "master" ]
    tags:
      - "v*.*.*"

jobs:

  auto-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Create Unity build
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2019.4.31f1
          buildMethod: Exporter.Export
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Upload built unitypackage
        uses: actions/upload-artifact@v2
        with:
          name: Unitypackage
          path: PackageExporter/DecentM.AutoDeploy.unitypackage

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          files: |
            PackageExporter/*