name: build

on:
  push:
    branches: [ "master" ]
    tags:
      - "v*.*.*"

jobs:

  auto-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Write auth data to disk
        run: |
            set -ex
            mkdir -p .ignored
            touch .ignored/auth.json
            echo '{"username":"${{ secrets.VRC_USERNAME }}","password":"${{ secrets.VRC_PASSWORD }}","otpToken":"${{ secrets.VRC_OTP_TOKEN }}"}' > .ignored/auth.json

      - name: Create Unity build
        uses: DecentM/unity-builder@7baa3abbb98952b3d6d7c3748f9c2f2027f2933f
        with:
          unityVersion: 2019.4.31f1
          buildMethod: DecentM.AutoDeploy.CI.BuildLoginUpload
          customParameters: -nographics
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
